<a href="https://colab.research.google.com/github/MarohBJoshua22/Undergrad-Project/blob/main/SA_Grooming_Detection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inserting the Perverted justice dataset (PJ)

In [ ]:
import pandas as pd

dfpj = pd.read_csv('/content/drive/MyDrive/merged-csv-files.csv')
dfpj.shape

(58488, 4)

In [ ]:
dfpj = dfpj[['BODY']].rename(columns={'BODY': 'Text'})
dfpj = dfpj[['Text']]
# dfpj['Text'] = dfpj['Text'].astype(str)  # Convert to string type
dfpj['label'] = 'Grooming'  # Binary label for non-grooming
dfpj = dfpj.drop_duplicates(subset='Text') #removing duplicates
dfpj = dfpj.dropna() #removing null values

import re
# Function to remove symbols not followed by letters
def remove_symbols(text):
    return re.sub(r'[^A-Za-z0-9\s]+(?=\s|$)', '', text)
dfpj['Text'] = dfpj['Text'].apply(remove_symbols)

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
def remove_stopwords(text):
    from nltk.corpus import stopwords
    stop_words = set(stopwords.words('english')) | custom_stop_words
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

custom_stop_words = set()
def add_stopwords(new_stopwords):
    global custom_stop_words
    custom_stop_words.update(new_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Custom stop words

In [ ]:
add_stopwords([
    'cat', 'cat:-)', 'catagory', 'catch', 'catches', 'cats', 'cats?', 'caucasian,', 'caucios', 'caues', 'caugh', 'caught', 'caught?', 'cause', 'cause,', 'cause...ur', 'cause..it', 'causes', 'caust', 'caut', 'cautious', 'cauz', 'cauz?', 'cauzed', 'cavalier', 'cb', 'ccause', 'ccc?', 'cd', 'cds', 'cds..but', 'ceck', 'cedar', 'cel', 'celebration', 'celebrity.', 'celest', 'cell', 'cell,', 'cell..', 'cell..but', 'cell?', 'cellie', 'cellphone?', 'cells', 'celly', 'cemetary', 'cent', 'center', 'center??', 'centerd', 'centre', 'cents', 'ceot', 'cept', 'cereal', 'cereal?', 'cererial', 'certain', 'certificat', 'certifice', 'chacklates', 'chaining', 'chains', 'chair', 'challange?', 'challenge', 'challenging', 'champ', 'champ?', 'chance', 'chance,', 'chance,,,cats', 'chance..i', 'chance?', 'changd', 'change', 'change?', 'changed', 'changed,', 'changes', 'changin', 'changing', 'channel', 'chapped', 'chapstick', 'char4ng', 'charge', 'charged', 'charged...brb', 'charger', 'chargin', 'charging', 'charm', 'charming', 'chase', 'chat', 'chat!', 'chat:)', 'chat?', 'chated', 'chatiing', 'chating', 'chatlog', 'chatn', 'chatroom', 'chatrooms', 'chatrooms..take', 'chatrroom', 'chatted', 'chattin', 'chattin!', 'chattin?', 'chatting', 'chatting,', 'chatting?', 'chcken', 'cheap', 'cheaper', 'cheat', 'cheated', 'cheater', 'cheatin', 'check', 'check..', 'checked', 'checkers', 'checkin', 'checking', 'checkn', 'checkout', 'checks', 'cheeese', 'cheeks', 'cheer', 'cheerleader?', 'cheerleading', 'cheerleard', 'cheese', 'cheesecake', 'cheesecake?', 'cheez', 'chef', 'chek', 'chekin', 'chels', 'chemult', 'chepre', 'cherry', 'chess', 'chest..infact,', 'chest?', 'chevron', 'chevy', 'chewin', 'chewing', 'chicago', 'chick', 'chicken', 'chickin', 'chicks', 'chihuaha', 'chika', 'chiken', 'child', 'child..ull', 'children.', 'chill', 'chill,', 'chill...', 'chill?', 'chillin', 'chillin...', 'chilling', 'china', 'chinese', 'chinese,', 'chip', 'chip?', 'chips', 'chips,', 'chips?', 'chit', 'choc', 'chocalae', 'chocalate', 'chocklate', 'chocklates', 'choclet', 'chocolate', 'chocolatemilk', 'choice', 'choice...', 'choice?', 'choices', 'choices?', 'choises', 'choked', 'choose', 'choosing', 'chopchop', 'chopped', 'chores', 'chores?for', 'chose', 'chow', 'chris', 'chrismas', 'christ', 'christian', 'christine,', 'christmas', 'christmas!:x', 'christmas?', 'chubby', 'church', 'chuzzle', 'chyll', 'chz', 'ciao', 'cigarette', 'cigs', 'cincinatti', 'cincinetti', 'cincinnati', 'cincy', 'cinderella', 'cindi.', 'cindy', 'cindy?', 'cingular', 'circle', 'circles', 'circles,', 'circles...', 'circulation', 'cities', 'city', 'city?', 'citys', 'ckeeks', 'ckicken', 'claim', 'clap', 'clap?', 'clarkson', 'class', 'class,', 'class?', 'classes', 'classes?', 'classic', 'classmate', 'clause', 'clea.', 'clean', 'clean...', 'clean?', 'cleand', 'cleaned', 'cleaner', 'cleanin', 'cleans', 'clear', 'clear?', 'clearing', 'clemens', 'clen', 'click', 'clicked', 'clickin', 'client', 'clients,', 'cliffs', 'clifton', 'clik', 'climb', 'clinic', 'clint', 'clinton', 'clit', 'clit?', 'clntn?', 'clock', 'close', 'close,', 'close?', 'closed', 'closed?', 'closer', 'closer:)', 'closer?', 'closes', 'closest', 'closet', 'closet?', 'closets', 'closin', 'closin!', 'closing', 'clothes', 'clothes!', 'clothes,', 'clothes?', 'cloths', 'cloudy', 'clsoe', 'club', 'clubs?', 'cluch', 'cluching', 'clue', 'clue....wink,', 'clue?', 'clues?', 'clumbsy', 'cm', 'cme', 'cmon', 'cn', 'cna', 'cnn', 'cnt', 'co', 'coach', 'coast', 'coaster', 'coaster..cept', 'coasters!!!', 'coat', 'coat,', 'cobot', 'coc', 'cocamo', 'cock', 'cock?', 'cocks', 'cocky,,,but', 'cocomo?', 'code', 'code?', 'codean', 'codephrase', 'coffee', 'coffin', 'coffin?', 'coin', 'coin?', 'coke', 'coke,', 'cokes', 'col', 'colar', 'colars', 'cold', 'cold!', 'cold!!!', 'cold...', 'cold?', 'colda', 'colege?', 'colesburg', 'collect', 'collects', 'colledge?', 'college', 'college....', 'collins', 'cologne', 'coloma', 'color', 'color.', 'color?', 'color?let', 'colorado', 'colorful...but', 'colors', 'colour', 'columbia', 'columbus', 'columbus,', 'columbus?', 'com', 'com/keri_', 'comapny:)', 'comb', 'combat', 'comdom', 'comdoms', 'comdomz', 'come', 'come,', 'come/', 'come?', 'comeand', 'comeback', 'comedies', 'comedies,', 'comedown', 'comedy', 'comedy,', 'comedyalso', 'comein', 'comeon', 'comeonline?', 'comes', 'comez', 'comforatble', 'comfort', 'comfortable', 'comfortble', 'comfotable', 'comfy', 'comfy?', 'comidy', 'comin', 'comin?', 'coming', 'coming!!', 'coming?', 'comletley', 'command', 'comment', 'comments', 'common', 'communicate', 'communication', 'comon', 'comp', 'comp-', 'comp--', 'comp?', 'companies', 'company', 'company:d', 'company?', 'companys', 'compared', 'comparising', 'comparison..hope', 'compatible', 'competing', 'competion', 'competition', 'complain', 'complaining', 'complaint', 'complaints', 'complete', 'completely', 'completley', 'completly', 'complex', 'complicated', 'compliment', 'compny', 'compressor', 'compter', 'comptuer', 'computer', 'computer.', 'computer?', 'computers', 'computers?', 'computr', 'computrs', 'compy', 'concentrate', 'concern:', 'concerned', 'concerned.', 'concerned...but', 'concert', 'concider', 'concubines', 'condems', 'condom', 'condom,', 'condom?', 'condoms', 'condoms?', 'condoms??', 'condomz', 'conduct', 'condum', 'condums', 'conference', 'confession', 'confidance', 'confidence', 'confident', 'confirm', 'confuse', 'confused', 'confused,', 'confused...ok', 'confused?', 'confusin', 'confusing', 'connection', 'connection,', 'connections', 'consider', 'consideration', 'considered', 'constitution', 'constuction', 'consultant', 'contacs', 'contact', 'contacted', 'contacts', 'contacts??', 'conter', 'contest', 'continue', 'continued', 'contract', 'control', 'control?', 'controll', 'convenient', 'convenient!', 'convenient...so', 'conventions', 'conversation', 'conversations',
     'huh', 'huh,', 'huh?', 'huh??', 'huh?lol', 'huh?well,', 'hullllllllllllllllllllllllllllllo', 'hum', 'human', 'humm', 'humor', 'hun', 'hundred', 'hung', 'hung?', 'hunger', 'hungry', 'hungry!', 'hunnie', 'hunnie....ur', 'hunnie....who', 'hunnoie', 'hunny', 'hunt', 'huntington', 'hurin', 'hurray', 'hurrican', 'hurries', 'hurrrrrryyyyy', 'hurrrrry', 'hurry', 'hurry,', 'hurt', 'hurt...did', 'hurt?', 'hurt???????', 'hurting', 'hurtnow', 'hurts', 'hurts,', 'hurts?', 'hury', 'hush', 'hush!', 'hush,', 'huston', 'hut', 'hut?', 'huuuuuuury', 'huwell', 'hvae', 'hve', 'hw', 'hw?', 'hws', 'hwy', 'hwy16', 'hy', 'hymen', 'hymian', 'hyped', 'hyper', 'hypithetical', 'hypnotiz', 'hypnotize', 'hypnotizing', 'i', 'i-)', 'i-)i-)i-)i-)i-)i-)i-)i-)', 'i-)i-)i-)i-)i-)i-)i-)i-)i-)i-)', 'i-10', 'i...', 'i...dont', 'i.d.', 'i618-889-6163', 'i9', 'i9m', 'i;l', 'i;ll', 'i;m', 'i?', 'i_8u_raw', 'iabbay', 'iabout', 'iaint', 'iam', 'iambic', 'iant', 'ianta', 'ic', 'ic,', 'ic..so', 'icant', 'ice', 'ice?', 'icecream?', 'ick', 'ick!', 'icky', 'icky?', 'id', 'id!!', 'id?', 'idaho', 'idc', 'iddnt', 'ide', 'idea', 'idea,', 'idea..leave', 'idea?', 'ideas', 'ideas?', 'idid', 'ididnt', 'idiot', 'idiots', 'idk', 'idk,', 'idk.', 'idk..', 'idk....', 'idk...didnt', 'idk...havent', 'idk...like', 'idk...wish', 'idk..lol', 'idk..ur', 'idk..wheetbix..banana...milk...oj...but', 'idk..why', 'idk..wish', 'idk8-|', 'idk?', 'idol?', 'idont', 'idunno', 'if', 'if....or', 'if?', 'iffen', 'ifi', 'iforget', 'ifreinds', 'ifriends', 'ifthey', 'ifu', 'ifur', 'ig', 'iget', 'iggy', 'iggy?', 'iggyd', 'ight?', 'ignore', 'ignored', 'ignoring', 'igot', 'iguess', 'ihadminewhen', 'ihave', 'ihear', 'iim', 'iis', 'ij', 'ike', 'ikewl', 'iknow', 'il', 'ilegal?', 'ilike', 'ilke', 'ill', 'ill,', 'ill.', 'ill..what', 'illbe', 'illegal', 'illinois', 'illl', 'im', 'im?', 'ima', 'imagination', 'imagine', 'imagining', 'imback', 'imbearasing', 'imbearesed', 'imean', 'imed', 'iment', 'imf', 'imglad', 'imi', 'imin', 'imma', 'immature', 'immature...cause', 'immediate', 'imn', 'imnot', 'impatient', 'imperal', 'imperial', 'imperial?', 'importance..:(', 'important', 'importnat', 'importnt', 'imposible', 'impossible', 'ims', 'imthinking', 'imviroment', 'imy', 'in', 'in,', 'in.', 'in2', 'in:)', 'in?', 'ina', 'inaw-', 'incase', 'incest', 'inch', 'inches', 'inches?', 'incident.', 'including', 'incomin', 'incoming', 'indeed', 'independence', 'indian', 'indiana', 'indoor', 'industrial', 'industry', 'indy', 'indy--but', 'ineed', 'iner', 'ineternet', 'infact', 'infact...she', 'info', 'infomercials!', 'information', 'inforse', 'infront', 'ingoring', 'inheritence...millions', 'initials', 'inject', 'injured', 'inn', 'inoocent', 'inportant', 'insane', 'inscest', 'insert', 'inside', 'inside...', 'inside?', 'insides', 'inspiring', 'install', 'installing', 'instant', 'instead', 'instead?', 'insted', 'insted?', 'instinct', 'instruments', 'instruments?', 'insurance', 'insure', 'int', 'intamant', 'intellectual--lol', 'intelligent', 'intemately', 'inteqnet', 'inter', 'intercorse', 'intercourse', 'interest', 'interested', 'interested?', 'interestin', 'interesting', 'interesting,', 'interesting?', 'interests', 'interior', 'international', 'internet', 'internet?', 'interresting', 'interrupt', 'interrupted', 'intersted', 'intertaind', 'interview', 'interview,', 'interview?', 'into', 'into?', 'intop', 'intown', 'intrsect', 'intruble', 'intrview', 'invalved', 'inverter', 'invisible', 'invisible...so', 'invitation', 'inviting', 'involve', 'involved', 'involves', 'inxcess:', 'io', 'iot', 'iowa', 'iowa.', 'iowa?', 'ipod', 'iquor', 'iraq', 'iraq?', 'irl', 'iron', 'ironing', 'is', 'is,', 'is---$$$---:-p', 'is.', 'is...', 'is...like', 'is..he', 'is?', 'is??', 'ise', 'isee', 'island', 'island?', 'isnt', 'issue', 'ist', 'it', 'it!', 'it!!', 'it!!!', 'it*', 'it,', 'it,,,im', 'it-he', 'it.', 'it..', 'it...', 'it....', 'it.....lol', 'it....i', 'it....was', 'it...cause', 'it...depends', 'it...ewwwww', 'it...guys', 'it...it', 'it...just', 'it...later', 'it...lol', 'it...lolololololol', 'it...the', 'it...u', 'it..but', 'it..did', 'it..give', 'it..i', 'it..ill', 'it..just', 'it..lol', 'it..no', 'it..or', 'it..see', 'it..so', 'it..that', 'it..thats', 'it..what', 'it..will', 'it..yahoo', 'it/', 'it?', 'it??', 'it?is', 'it?right?', 'italian', 'italy...he', 'itch', 'itches..lol', 'itchy?', 'itd', 'ith', 'ithats', 'ithuh', 'itis', 'itll', 'itmore', 'its', 'itself', 'itself,', 'itself?', 'itsnice', 'itsokay', 'itunes', 'itup', 'itw', 'itwill', 'itwould', 'ity', 'itz', 'iu', 'iur', 'ivce', 'ive', 'ived', 'iw', 'iwanna', 'iwant', 'iwas', 'iwhat', 'iwill', 'iwll', 'iwould', 'iy', 'iz', 'j', 'j/k', 'j/k..u', 'j/w', 'j/w..cause', 'j/w..hope', 'j?', 'jac', 'jaccuzzi?', 'jack', 'jacked', 'jacket', 'jacking', 'jackson', 'jacksonville', 'jacuzzi', 'jacuzzi?', 'jade', 'jaden', 'jail', 'jail!!', 'jail?', 'jakson', 'jamaca', 'james', 'jammer', 'jammerz', 'jammies', 'jammies?', 'jan', 'jan?', 'january', 'janurary', 'japan', 'japan,', 'japanese', 'japanise', 'jared', 'jarome', 'jason', 'jason,', 'jason?', 'jax', 'jd', 'jealous', 'jealous?', 'jealousof', 'jean', 'jeans', 'jeans,', 'jeans...wish', 'jeep', 'jeez', 'jellouse', 'jelly', 'jelous', 'jen', 'jenkins', 'jenkis', 'jennys', 'jerk', 'jerking', 'jerks', 'jerome', 'jerome?', 'jerri', 'jerry', 'jes', 'jess', 'jess,', 'jess...be', 'jess...i', 'jess...whole', 'jess..ur', 'jess?', 'jess?im', 'jess?we', 'jess_n_cali@yahoo.com', 'jessica', 'jessica?u', 'jessie', 'jesus', 'jet', 'jetpacksidekick@aol.com', 'jew', 'jewerley', 'jfk', 'jim', 'jj', 'jjust', 'jk', 'jkn', 'jm', 'job', 'job,', 'job,,,i', 'job..dont', 'job?', 'jobs?', 'jog', 'john', 'john?', 'johnson', 'join', 'jointed', 'joke', 'jokes', 'jokin', 'jokin.......that', 'joking', 'jonalyn', 'jones', 'jordache?', 'jose', 'jose,', 'jose.', 'jose..but', 'jose..have', 'josh', 'josie', 'joy', 'joystick', 'jp', 'jr', 'jrock', 'jst', 'jsut', 'juction', 'judge', 'judgin', 'juice', 'juices', 'juicve', 'juist', 'juliet', 'july', 'jump', 'jumped', 'jumpin', 'jumping', 'june', 'june?', 'june?but', 'jungle', 'junior', 'junkyard', 'junkyard?', 'junkyards?', 'jus', 'juss', 'just', 'justice', 'justice,', 'justified', 'justin', 'justin,', 'justs', 'justthe', 'justtoo', 'jut', 'jw', 'k', 'k!', 'k,', 'k,,,sounds', 'k.', 'k..lol', 'k;)nite', 'k?', 'k??', 'kalamazoo', 'kanow', 'karate', 'kay', 'kay,', 'kay.', 'kay?', 'kayla', 'keep', 'keepin', 'keeping', 'keepings', 'keepit', 'keeps', 'keith', 'kel', 'kellie', 'kelly', 'kelly,', 'kenosha', 'kenosha,,,', 'kentucky', 'kept', 'keri', 'keri_keepin', 'ketchup', 'ketchup!', 'ketchup!!!!!', 'kevin', 'kew?', 'kewel', 'kewelllllllllll', 'kewl', 'kewl!', 'kewl!!', 'kewl!!!', 'kewl!!!!', 'kewl!!!!!', 'kewl!!!!!!', 'kewl!!!!!!!!!', 'kewl,', 'kewl:)', 'kewl?', 'kewlgood', 'kewlio', 'kewt', 'kewwwll', 'key', 'keyboard', 'keybording', 'keys', 'kia', 'kick', 'kickboxing', 'kicked', 'kid', 'kid,', 'kid?', 'kiddies', 'kiddin', 'kidding', 'kidding!', 'kidding..oh', 'kidna', 'kidnap', 'kidnapped?', 'kido', 'kids', 'kids,', 'kids.', 'kids?', 'kiknda', 'kill', 'killed', 'killer', 'killer?', 'killers', 'killing', 'killr', 'kills', 'kin', 'kin?', 'kind', 'kind?', 'kinda', 'kinda.', 'kinda...', 'kinda..just', 'kinda:', 'kinds', 'kindz', 'king', 'king,', 'kinky', 'kir', 'kiser', 'kitchen', 'kitten', 'kitten....', 'kitty', 'kitty.', 'kk', 'kk!!', 'kk,', 'kk.', 'kk....', 'kk?', 'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk', 'klikin.....should', 'kn', 'knd', 'knda', 'knee', 'knees', 'knew', 'knid', 'kniew', 'kno', 'kno!', 'kno,', 'kno-', 'kno--i', 'kno-wut', 'kno...i', 'kno?', 'knock', 'knock?', 'knocked', 'knocking', 'knoe', 'knotting', 'knotting?', 'know', 'know!', 'know!!', 'know!!!!', 'know**', 'know,', 'know,,,im', 'know,,,its', 'know,,,maybe', 'know.', 'know..', 'know...', 'know....ill', 'know....its', 'know....ptooey', 'know...but', 'know...i', 'know...im', 'know...l', 'know...not', 'know...u', 'know..but', 'know..did', 'know..games', 'know..hey', 'know..i', 'know..maybe', 'know..places', 'know..still,', 'know..too', 'know/', 'know:p', 'know?', 'know?friends?school?', 'knowan', 'knowher', 'knowin', 'knowing', 'knowledge', 'known', 'knows', 'knoxville', 'knw', 'knwo', 'knwo?', 'kombat', 'konw', 'koo', 'kook', 'kool', 'kool!', 'kool!!', 'kool!!!', 'kool!!!!', 'kool,', 'kool?', 'kooler??', 'koool', 'korea', 'korny', 'kow', 'krayzie', 'kristen', 'kristen?', 'ks', 'kshe', 'kutcher', 'kwon', 'ky', 'ky.', 'kylie', 'l', 'l)', 'l.a', 'l.a.', 'l.a.?', 'l00k', 'l0l', 'l0ol', 'l8er!', 'l8ter', 'la', 'lab', 'labtop', 'lace', 'lacey', 'lack', 'ladies', 'lady', 'ladybass.', 'ladys', 'laet', 'laff', 'laffin', 'lagrand?', 'laguna', 'laid', 'lake', 'lake,', 'lakefront', 'lakewood', 'lame', 'lame!', 'lamplight', 'land', 'land?', 'landing', 'landing.', 'lands', 'lands.', 'lanes', 'langaray', 'langerie', 'langueg', 'lap', 'lap...', 'lap?', 'laptop', 'laptop?', 'las', 'lasagana', 'lasangna', 'last', 'lastnight', 'lastnite', 'lat', 'latar', 'late', 'late!', 'late,', 'late..like', 'late?', 'late?its', 'lately', 'lately...all', 'later', 'later!', 'later!!', 'later,', 'later...', 'later.....', 'later...if', 'later..id', 'later?', 'laterz', 'latest', 'latino', 'latino,', 'latr', 'lauderdale', 'laugh', 'laugh!', 'laugh?', 'laughd', 'laughed?maybe', 'laughin', 'laughing', 'laughing,', 'laughing..then', 'laughjhing', 'lauging', 'laundry', 'laundry...again', 'laundy', 'launrdry', 'lave', 'law', 'law...im', 'law?', 'lawton', 'lawyer', 'lay', 'laying', 'layout', 'lays', 'laytar', 'laywers', 'lazy', 'lb..but', 'lbs,', 'ld?', 'ldest', 'lds', 'lds?', 'lead', 'leading', 'leads', 'learning', 'lease', 'least', 'least.', 'leather', 'leav', 'leav;in', 'leave', 'leave,', 'leave---i', 'leave..', 'leave...', 'leave?', 'leaves', 'leaves!', 'leaves,', 'leaves....how', 'leaves?', 'leavin', 'leavin?', 'leavin??', 'leaving', 'leaving,', 'leaving?', 'lebanon', 'lectured', 'lectures', 'lecturing', 'lee', 'leest', 'left', 'left..', 'left...to', 'left..have', 'left..so', 'left?', 'left?:(', 'left???', 'leg', 'legal', 'legal,greys', 'leggins', 'leggs',
    'aaaaaaaahhhhhhhhh', 'aaround', 'ab?','ababy','abbreviations','abck', 'abd','abit','able','able2','abot','abotu','abou','abought','about','about----2','about.','about?','abouut',
    'above','abovt','abs','absolutely','absolutly','abuot?','ac','ac/dc','academic','academy','acall','acar','acat','accedpt','accent','accent','accept','acces','access','accident','accidental','accidentally','accidently','accord','according','account','account..', 'account?','accpt', 'accusing', 'ace', 'ach', 'achine--lol', 'acholic' 'ack', 'acl?','aconference', 'acording','acres','across', 'act','actaully', 'acting', 'action', 'active', 'activities','actors','actress','acts','actually','actualy','actully', 'aday','add','adddress','added','addy', 'admiring','admit','adn','adog','adopted' ,'adress','advanatge','advanced','adventure','adventurous','advice','advice..when','ae','afect','afew', 'afford','affter','afraid','after','afternoon','afterward','afterwards','aftr','aftter','again','ago','agreement','agustt','aguy','ahh','ahhaah','ahhh','ahhhh','ahhhhh','ahhhhhhh','ahold','ahoo','ahuh','ahve','aids','aim','aimee','aint','ainta','air','airplane','airplanes','airport','airport','ajob','ake','akward','al','alamo','alarm','alaska','albertsons','albion','album','alcohol','alcoholic','aleast','alen','alert','algebra','algi','ali','aligator','alike','alil','alil...ur','alinve','alittle','alive','alive','all','allergic','allergies','allergkic','alley','allie', 'allow','allowance','allowed','allready','allredy','allright','allthe','allu','alluring but','ally','almighty','almoast','almost','alnighter','alo','alomost','alomst','along' ,'alongtime','alot' ,'alphabetical','already','already', 'alreay','alright', 'alrite', 'also','altho', 'although', 'alwasy', 'alway', 'alwayas', 'alwayes', 'always', 'always', 'ama','amanda','amazing','ame','amee','america','america','american','amit','amonth','amonth?','amotor','amount','amusement','amy','amybe','anaheim' ,'anatamy','and','andersen','angelic' ,'angels','angle','anhy','anice','animal','animals','ann','anna','annnnnd','annnnnnnd','announced','annoying','anof','anonymous','anooying','another','another..that','anothr','ans','anser','ansewr?','answa','answer', 'answered','answerin','answering','answerr','answers','answr','ant','antana','anthing','anthing..so','anthting','anuything','anways','anwyay','anwyays''anxious', 'anyhting','anyone','anyother','anythings','anythjing','anytihng','anytime','anyting','anyting','anytome','anywa','anyware', 'anyway','anyway...so','anyway..let','anyway..so','anyway?','anyways','anyways....what','anyways..and','anyways..im','anyways..sometime','anyways..sorry','anyways',
    'anywya','ao','aobut','aobut?','aoff','aol','aorund','aot','aound','aout','aout','apart','apart...2','apartment','apartment?','aphrodisiac','aplace','aple','appointment', 'appraisal', 'appreciate', 'approach', 'appropriate', 'appropriate..', 'approve', 'approved?', 'approximate','approximately','appt', 'appts', 'april', 'apt', 'apt?', 'apts', 'aquarius', 'ar', 'arbor', 'arbys..what', 'arcade', 'archive','archives','archives?','Archiving','are', 'are!', 'are!!', 'are!!!', 'are,', 'are,,,except', 'are.', 'are...', 'are....', 'are?', 'area', 'area,', 'area?','areas', 'areas,', 'areay', 'aren','arent', 'arent...', 'areolas', 'argh', 'argh,', 'argue', 'argument....lol', 'arik', 'arilines', 'arlier', 'arm', 'armpit?!','armpits', 'arms', 'arms!!','arms..and', 'army', 'army?', 'armysgt1961', 'arnt', 'aroudn', 'aroun', 'around', 'around,', 'around..with', 'around3:00', 'around?', 'arrange', 'arranged','arrested', 'arrives', 'arrow', 'art', 'art?', 'arts', 'arway', 'as', 'as,', 'aschutze@msn.com', 'asekd', 'ash', 'ashame', 'ashamed', 'ashley', 'ashton', 'ashville',
    'asian', 'aside', 'ask', 'ask,', 'ask..lol', 'ask?', 'askd', 'aske', 'asked', 'asked,', 'askes', 'askin', 'askin?', 'askin?someone', 'asking', 'asking,', 'asking..',
    'asking.....what', 'asking?', 'askn', 'asks', 'asl', 'asl?', 'asleep', 'asleep!', 'asleep,', 'asleep?', 'aslep', 'aslo', 'aslong', 'asnt', 'asoon', 'ass', 'ass,',
    'ass-faced', 'ass-lol', 'ass...im', 'ass?', 'asses', 'assests', 'assests..especialy', 'asshole', 'assist', 'assme', 'assume', 'assumed', 'assuming', 'astoria',
    'astringent', 'at', 'at---excatly', 'at?', 'atcha', 'atched', 'ate', 'ate,', 'athletic', 'athletic,', 'atit', 'atl', 'atlanta', 'atleast', 'atlk', 'atm', 'atmirror',
    'atomosphere', 'atracktive', 'atracted', 'atre', 'att', 'attached', 'attack', 'attacked', 'attention', 'attitude', 'attn', 'attracted', 'atw', 'atw?', 'atwin', 'auditin?',
    'audition', 'audition,', 'aug', 'augh,', 'august', 'august!', 'august?', 'aunt', 'aunt?', 'aunts?', 'aussie', 'austin', 'australia', 'australia?', 'australian', 'australin',
    'auto', 'automatic', 'automaticly', 'automechanic', 'auz', 'avaar', 'avail', 'available', 'available?', 'avatar', 'ave', 'ave,', 'avenger', 'avg', 'avoiding', 'avter', 'avy', 'aw',
    'awake', 'awake!', 'awake,', 'aware', 'awarkard', 'away', 'away....', 'away...maybe', 'away..they', 'away..why', 'away?', 'awe', 'aweome', 'awesme', 'awesom', 'awesome', 'awesome!',
    'awesome!!', 'awesome!!!', 'awesome!!!!', 'awesome!!!1', 'awesome,,,wont', 'awesome...', 'awesome..dont', 'awesomely', 'awesomeme', 'awesum', 'awesum!!', 'awful', 'awful!!', 'awhile', 'awhile...and','awhile...but', 'awhile?', 'awhile@-)', 'awkward', 'awsome', 'awt', 'aww', 'aww,', 'aww...i', 'aww...well', 'aww..i', 'aww..that', 'awww', 'awww!', 'awww,', 'awww--', 'awww....', 'awww...me','awwww', 'awwww!', 'awwww,', 'awwww.', 'awwwww', 'awwwww,', 'awwwwww', 'awwwwww.', 'awwwwwww', 'awwwwwwww', 'awwwwwwww,', 'awwwwwwwwwww', 'awwwwwwwwwwww', 'awwwwwwwwwwwwwwwwwww','awwwwwwwwwwwwwwwwwwwwwwwwwww:(', 'awy', 'ay', 'az', 'az,', 'az?', 'az?i', 'b', 'b-)', 'b-day', 'b-day.', 'b-day?', 'b/f', 'b/f--:-p', 'b/f-:-p', 'b/f-g/f..jsut', 'b/f-if', 'b/f...dont','b/f..if', 'b/f..ur', 'b/f?', 'b/f?or', 'b/fast', 'b/fs', 'b/k', 'b4', 'b4,', 'b4?', 'b4?r', 'b:)', 'ba', 'babble', 'babe', 'babe,', 'babe...as', 'babe...i', 'babe...is', 'babe...its','babe...less', 'babe...so', 'babe...ur', 'babe..i', 'babe..or', 'babe..thats', 'babe..u', 'babe:)', 'babe:-*', 'babe?', 'babe?how', 'babies', 'babiesit','babt', 'baby', 'baby!', 'baby!!','baby,', 'baby,,,:-*', 'baby...me', 'baby...thats', 'baby.lol', 'baby?', 'baby?hes', 'babygirl', 'babys', 'babysat', 'babysit', 'babysitted', 'babysitter', 'babysitter?', 'babysitters', 'babysittin','babysittin?', 'babysitting', 'bac', 'bacg', 'back', 'back...', 'back..sorry', 'back:)', 'back?', 'back?when?tomorrow', 'backdoor', 'backflips', 'background', 'background?', 'backing', 'backkkkkkkkkkk', 'backs',
    'backup', 'backwards', 'backwith', 'backyard', 'bad', 'bad!', 'bad,', 'bad.', 'bad..', 'bad...', 'bad..i', 'bad..is', 'bad..u', 'bad?', 'bad?!', 'badly', 'bag', 'baggy', 'bags', 'bah', 'bailed', 'bailout', 'bait','bak', 'bake', 'baking', 'bakini', 'ball', 'balls,', 'ballys?', 'band', 'band?', 'bandaid', 'bands', 'bane','bank', 'baout', 'bar', 'barbies', 'bare', 'bareeeeeeeeeeeely', 'barely', 'barf', 'baristo', 'baristo?',
    'barkingout', 'barnes', 'bars', 'bartender?', 'baseball', 'baseball?', 'basic', 'basically', 'basketball', 'basketball,', 'basment', 'bastard', 'bastard!', 'bat', 'bath', 'bath,', 'bathes', 'bathing', 'bathroom','bathroom.', 'bathroom?', 'bathrooms', 'baths', 'bathtub', 'bathtub!!!', 'bathtube', 'battalion', 'batteries', 'battery', 'battry', 'battry!', 'baut', 'bawl', 'bay', 'bay?', 'baybee', 'baybees', 'bb', 'bback', 'bball',
    'bben', 'bbiab', 'bbl', 'bc', 'bch', 'bday', 'bday,', 'bday.', 'bday?', 'bdul', 'be', 'be!', 'be,', 'be,,,im', 'be..thanks', 'be4', 'be?', 'bea', 'bea?', 'beable', 'beach', 'beach?', 'beaches', 'beaches?', 'beaching',
    'beacuse', 'beacyh', 'beale', 'bean', 'beans', 'bear', 'beard', 'bears', 'beat', 'beatin', 'beating', 'beats', 'beauty', 'bec', 'became', 'becareful..once', 'because', 'becauz', 'becca', 'becca?', 'beccas',
    'becky', 'become',   'becomes', 'becuase', 'becuz', 'bee', 'beeca', 'beeen', 'beef', 'beeing', 'beely', 'been', 'been?', 'been??',
    'beep', 'beer', 'beer,', 'beer?', 'beers', 'beers,', 'beeter', 'befor', 'before', 'before,', 'before?', 'beg', 'begged', 'beggin', 'begin', 'begining', 'behalf....and', 'behave', 'beher', 'behere', 'behind', 'behind*', 'beige', 'bein', 'being', 'bejeez', 'beka', 'beka.', 'beleave', 'beleaving', 'beleive', 'beleve', 'believe', 'believe,', 'belive', 'bell', 'bell?', 'bellevie', 'belleville', 'bellflower', 'bellsouth', 'belly', 'belly*', 'belly,', 'belly?', 'belong', 'belongs', 'below', 'belt', 'bemarried', 'ben', 'bench', 'benches', 'bend', 'bend....sorry', 'beneath?', 'benning', 'benning?', 'bent', 'bepends', 'bermuda,', 'berries', 'berry', 'beside', 'besides', 'besides,', 'besito', 'besito?', 'best', 'best?', 'bestest', 'bet', 'bet!', 'beter', 'beth', 'bethany,', 'betomorrow', 'bets', 'betta', 'betta?', 'bette', 'better', 'better!!!', 'better,', 'better...i', 'better...myspace', 'better..and', 'better..as', 'better..i', 'better..otherwise', 'better:)', 'better?', 'betterer', 'bettert', 'betting', 'bettr', 'between', 'bewteen', 'bewtteen', 'beyond', 'bf', 'bf*', 'bf,', 'bf..lol', 'bf/gf', 'bf?', 'bfast', 'bff..shes', 'bfore', 'bfriend', 'bfs', 'bfs.', 'bfs?', 'bg', 'bi', 'bi----', 'bible..he', 'bicycle?', 'bicycles?', 'big', 'big!!\\', 'big,', 'big---only', 'big...maybe', 'big..lol', 'big?', 'big?!', 'bigg', 'bigge', 'bigge,', 'bigger', 'bigger?', 'biggest', 'bigggggggggggg', 'biggie', 'bigy', 'bike', 'bikes', 'bikes?', 'bikini', 'bikini!!', 'bikini?', 'bikinis', 'bill', 'bill,', 'billie', 'bills', 'bills..yuck..what', 'bills?', 'biological', 'bird', 'bird,', 'birds', 'birt', 'birth', 'birthcert', 'birthcertif', 'birthcertificate', 'birthcontrol', 'birthcontrol?', 'birthcontroll', 'birthdate', 'birthdate?', 'birthday', 'birthday,', 'birthday?', 'birtheday', 'birthstone', 'bishop', 'bismol', 'bit', 'bit!!', 'bit,', 'bit,,,x0x0', 'bit...', 'bit?', 'bitch', 'bitches..', 'bite', 'bith', 'biting', 'bitrh', 'bitter', 'bitty', 'biz', 'bizness', 'bj', 'bjs', 'blac', 'black', 'black,', 'black?', 'blackailer', 'blackmailer', 'blade,', 'blah', 'blam', 'blame', 'blamed', 'blames', 'blank', 'blanket', 'blanket,', 'blankets?', 'blankie', 'blankies', 'blast', 'blast..roll', 'blazin', 'blech', 'bleed', 'bleeding', 'bleeds', 'bleh', 'blessings', 'blew', 'blind', 'blind?', 'blinky', 'blo', 'block', 'blocked', 'blocks', 'blog,', 'blond', 'blond?', 'blonde', 'blonde,', 'blonde?', 'blood', 'blother', 'blow', 'blown', 'blowpops', 'blue', 'blue,', 'blue?', 'blueberries', 'bluegill', 'blunt', 'blunt..hope', 'blunt?', 'blurry', 'blurt', 'blury', 'blush', 'blush!', 'blushing', 'blushing?', 'blvd', 'bnad?', 'board', 'boaring', 'boat', 'bodies', 'body', 'body,', 'body?', 'bodys', 'boi?', 'boing', 'boling', 'bone', 'boned', 'boned--wow-i', 'boner', 'boner?--lol', 'bones', 'bonita', 'bonus', 'bonus.', 'boo', 'boo!', 'boob', 'boobes?', 'booboo', 'boobs', 'boogeyman', 'book', 'book,', 'booked', 'booking', 'bookmark', 'books', 'boonies', 'booo', 'boooo', 'booooored', 'boost', 'boot', 'booted', 'booted!', 'booted,', 'booted?', 'booteed', 'booters', 'bootery', 'booth', 'bootin', 'boots', 'boottom','booze', 'borad', 'bord', 'bord!', 'bore', 'bored', 'bored...', 'bored.com', 'bored?', 'borin', 'borin,', 'borin?', 'boring', 'born', 'born:p', 'borrow', 'borrowed', 'borther', 'bos', 'boss', 'boss?', 'bossed', 'bossy', 'boston', 'boston,', 'boston?', 'bot', 'bot..lol', 'both', 'both!', 'both!!', 'both..', 'both?', 'bother', 'bothered', 'bothering', 'bothers', 'botht', 'botom', 'bots', 'bots..', 'bottom', 'bottoms', 'botu', 'bought', 'bouht', 'bounce', 'bout', 'bout...weed,', 'bout..do', 'bout?', 'bout?so', 'bow', 'bowl', 'bowlin', 'bowling', 'bowling,', 'bowling?', 'box', 'box?', 'boxer', 'boxer,', 'boxerbrief,', 'boxers', 'boxers?', 'boy', 'boy:)', 'boy?', 'boyf', 'boys', 'boys,', 'boys:|', 'boys?', 'boze', 'br', 'bra', 'bra?', 'brad', 'brain', 'brain?', 'brainer', 'brains', 'brake', 'brand', 'brandy', 'bras', 'bras,', 'brat', 'brat...', 'brat?', 'brave', 'brazil', 'brb', 'brb!', 'brb,', 'brb,k', 'brb..', 'brb...can', 'brb..im', 'bread', 'breafast', 'break', 'break!!', 'break?', 'breakfast', 'breakfast?', 'breakin', 'breaking', 'breaks', 'breast', 'breasts', 'breasts,', 'breath', 'breathe', 'breeze', 'brefs', 'breifs', 'brendan', 'brews?', 'brians', 'bribe', 'brick', 'bricktown?', 'bride', 'briefs', 'bright', 'brighten', 'brighter', 'brightn', 'brine', 'bring', 'bring?', 'bringin', 'bringing', 'brings', 'britest', 'brithday', 'brittney', 'bro', 'bro?', 'broadband', 'broght', 'broke', 'broke!', 'bronw', 'broom', 'bros', 'bros...', 'brother', 'brothers', 'brothers?', 'brought', 'brougt', 'brown', 'brown,', 'brownies', 'brr', 'brreast', 'brrrrrr', 'bruce', 'bruises', 'brush', 'brushin', 'brushy', 'brwn', 'brwn..it', 'brwn/blue', 'bs', 'bsides', 'bt', 'btw', 'btw,', 'btw......', 'btw?', 'bu', 'bubble', 'bubbles', 'buble', 'buciness', 'buck', 'buckles', 'bucks', 'bud,', 'buddies', 'buddy', 'buds', 'budys', 'buff', 'buff?', 'bug', 'buggin', 'bugging', 'build', 'buildin', 'building', 'building,', 'building?', 'builds', 'built', 'bulb', 'buld', 'buldings', 'buliding', 'bulletin', 'bullshitting.', 'bum', 'bummed', 'bummer', 'bump', 'bumped', 'bumpers', 'bumps', 'bumps?', 'bums', 'bunch', 'buncha', 'bunches', 'bundled', 'burbs..hang', 'burden', 'buren', 'burger', 'burgerer', 'burn', 'burnd', 'burned', 'burning', 'burns', 'bus', 'bus?', 'buses', 'buses?all', 'business', 'business,', 'busness', 'bust', 'bustd', 'busted', 'busy', 'busy,', 'busy...sorry...missed', 'busy?', 'busy?doin', 'busys', 'busyto', 'but', 'but,', 'but...', 'but...if', 'but?', 'butim', 'butt', 'butt?', 'butter', 'butterfinger', 'butterflies', 'butterfly', 'butthanks', 'button', 'buttoned', 'buttons', 'butts', 'buu', 'buut', 'buy', 'buy?', 'buyin', 'buying', 'buys', 'buyz', 'buyzy', 'buzy', 'buzz', 'buzz?', 'buzzed', 'buzzer', 'buzzin?', 'buzzz', 'buzzzzzzz', 'bvye', 'bw3', 'by', 'by?', 'bycycle', 'bye', 'bye!', 'bye!!!', 'bye..atleast', 'bye;)', 'bye?????', 'byeeeeee', 'bymyself', 'bytch', 'byw', 'byyeeee', 'c', 'c.', 'c...so', 'c...well', 'c...yeah,', 'c..so', 'c..swimmin?videos', 'c..was', 'ca', 'ca;m', 'ca?', 'cab', 'cabin', 'cable', 'caffene', 'caiught', 'cake?', 'cal', 'cali', 'cali?', 'cali?thats', 'calif', 'california', 'caling', 'call', 'call,', 'call.', 'call...', 'call..but', 'call/email/chat...with', 'call?', 'call?heres', 'calld', 'called', 'called,', 'called?', 'callege', 'callen', 'caller', 'callin', 'callin,', 'callin..', 'callin?', 'calling', 'calling/', 'calling?', 'calll', 'callr', 'calls', 'calls!!', 'calls...anyway', 'callz', 'caloosa', 'calw', 'calz', 'cam', 'cam...its', 'cam..and', 'cam..wud', 'cam?', 'camcel', 'came', 'camel', 'camera', 'camera?', 'cameras', 'cami', 'camo', 'camp', 'camp...i', 'camp?', 'camp?did', 'camper', 'campfire', 'campin', 'camping', 'camra', 'cams', 'can', 'can,', 'can...i', 'can?', 'canada', 'canada?', 'cancedl', 'cancel', 'canceled', 'canceled?', 'cancer', 'cand', 'candies', 'candle', 'candle,', 'candles', 'candles,', 'candy', 'candy,', 'canjust', 'cannont', 'cannt', 'canopy', 'cant', 'canton', 'canton?', 'cap', 'cape', 'caps', 'captain', 'captin', 'car', 'car!', 'car,', 'car.', 'car..', 'car...in', 'car..u', 'car?', 'car???', 'cara', 'cara,', 'caralina', 'card', 'card,', 'card....', 'card?', 'cards', 'cardz', 'care', 'care,', 'care-that', 'care...', 'care..honestly..and', 'care?', 'cared', 'career?', 'careful', 'careful!', 'careful!!', 'careful!!!', 'careful,', 'careful...', 'careful...u', 'carefully', 'cares', 'cares?', 'carful', 'cargo', 'carin', 'caring', 'carlona', 'carlos', 'carmax', 'carpedia', 'carpenter', 'carpet,', 'carrie', 'carried', 'carrier', 'carry', 'carrying', 'cars', 'cars,', 'cars.', 'cars?', 'carson', 'cartoon,', 'cartwheels', 'case', 'case,', 'case?', 'cases', 'cash', 'cash?', 'casino', 'casual,', 'casue', 'cat', 'cat:-)', 'catagory', 'catch', 'catches', 'cats', 'cats?', 'caucasian,', 'caucios', 'caues', 'caugh', 'caught', 'caught?', 'cause', 'cause,', 'cause...ur', 'cause..it', 'causes', 'caust', 'caut', 'cautious', 'cauz', 'cauz?', 'cauzed', 'cavalier', 'cb', 'ccause', 'ccc?', 'cd', 'cds', 'cds..but', 'ceck', 'cedar', 'cel', 'celebration', 'celebrity.', 'celest', 'cell', 'cell,', 'cell..', 'cell..but', 'cell?', 'cellie', 'cellphone?', 'cells', 'celly', 'cemetary', 'cent', 'center', 'center??', 'centerd', 'centre', 'cents', 'ceot', 'cept', 'cereal', 'cereal?', 'cererial', 'certain', 'certificat', 'certifice', 'chacklates', 'chaining', 'chains', 'chair', 'challange?', 'challenge', 'challenging', 'champ', 'champ?', 'chance', 'chance,', 'chance,,,cats', 'chance..i', 'chance?', 'changd', 'change', 'change?', 'changed', 'changed,', 'changes', 'changin', 'changing', 'channel', 'chapped', 'chapstick', 'char4ng', 'charge', 'charged', 'charged...brb', 'charger', 'chargin', 'charging', 'charm', 'charming', 'chase', 'chat', 'chat!', 'chat:)', 'chat?', 'chated', 'chatiing', 'chating', 'chatlog', 'chatn', 'chatroom', 'chatrooms', 'chatrooms..take', 'chatrroom', 'chatted', 'chattin', 'chattin!', 'chattin?', 'chatting', 'chatting,', 'chatting?', 'chcken', 'cheap', 'cheaper', 'cheat', 'cheated', 'cheater', 'cheatin', 'check', 'check..', 'checked', 'checkers', 'checkin', 'checking', 'checkn', 'checkout', 'checks', 'cheeese', 'cheeks', 'cheer', 'cheerleader?', 'cheerleading', 'cheerleard', 'cheese', 'cheesecake', 'cheesecake?', 'cheez', 'chef', 'chek', 'chekin', 'chels', 'chemult', 'chepre', 'cherries', 'cherry', 'chess', 'chest', 'chest,', 'chest..infact,', 'chest?', 'chevron', 'chevy', 'chewin', 'chewing', 'chicago', 'chick', 'chicken', 'chickin', 'chicks', 'chihuaha', 'chika', 'chiken', 'child', 'child..ull', 'children.', 'chill', 'chill,', 'chill...', 'chill?', 'chillin', 'chillin...', 'chilling', 'china', 'chinese', 'chinese,', 'chip', 'chip?', 'chips', 'chips,', 'chips?', 'chit', 'choc', 'chocalae', 'chocalate', 'chocklate', 'chocklates', 'choclet', 'chocolate', 'chocolatemilk', 'choice', 'choice...', 'choice?', 'choices', 'choices?', 'choises', 'choked', 'choose', 'choosing', 'chopchop', 'chopped', 'chores', 'chores?for', 'chose', 'chow', 'chris', 'chrismas', 'christ', 'christian', 'christine,', 'christmas', 'christmas!:x', 'christmas?', 'chubby', 'church', 'chuzzle', 'chyll', 'chz', 'ciao', 'cigarette', 'cigs', 'cincinatti', 'cincinetti', 'cincinnati', 'cincy', 'cinderella', 'cindi.', 'cindy', 'cindy?', 'cingular', 'circle', 'circles', 'circles,', 'circles...', 'circulation', 'cities', 'city', 'city?', 'citys', 'ckeeks', 'ckicken', 'claim', 'clap', 'cl',

    ])

In [ ]:
dfpj['Text'] = dfpj['Text'].apply(remove_stopwords)

dfpj.head(12000)

                                 Text     label
0                   dennis us soldier  Grooming
1                                  hi  Grooming
2                              old ru  Grooming
3                           13 old ru  Grooming
4                            u single  Grooming
...                               ...       ...
18160          nothing serious though  Grooming
18161  lol u trying get rid soemthing  Grooming
18164                  suuuuuure u ha  Grooming
18166                            wuld  Grooming
18167                        lol dont  Grooming

[12000 rows x 2 columns]

In [ ]:
dfpj.shape

(39807, 2)

# Inserting the twitter dataset

In [ ]:
dftw = pd.read_csv('/content/drive/MyDrive/twitter_training.csv')

dftw = dftw[dftw['Lexicon'] != 'Neutral']
dftw = dftw[dftw['Lexicon'] != 'Irrelevant']

In [ ]:
dftw.head()

,number,Borderlands,Lexicon,Text
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [ ]:
dftw = dftw[['Text']].rename(columns={'Text': 'Text'})
dftw['label'] = 'Non-grooming'  # Binary label for non-grooming
dftw = dftw.drop_duplicates(subset='Text') #removing duplicates
dftw = dftw.dropna() #removing null values

dftw['Text'] = dftw['Text'].apply(remove_symbols)

def remove_norm_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

dftw['Text'] = dftw['Text'].apply(remove_norm_stopwords)

In [ ]:
dftw.shape

(40286, 2)

In [ ]:
dftw.head(100)

                                                  Text         label
0                                  coming borders kill  Non-grooming
1                          im getting borderlands kill  Non-grooming
2                         im coming borderlands murder  Non-grooming
3                      im getting borderlands 2 murder  Non-grooming
4                        im getting borderlands murder  Non-grooming
..                                                 ...           ...
152  Ok LOVING (also seeing Take Baghdad anything g...  Non-grooming
153  Ok sir LOVING also playing Bombs Baghdad case ...  Non-grooming
154  Ok LOVING (also playing Bombs Earth anything g...  Non-grooming
155         uninstalled games make space Borderlands 3  Non-grooming
156            uninstall games make room Borderlands 3  Non-grooming

[100 rows x 2 columns]

# Combine Both Datasets

In [ ]:
combined_df = pd.concat([
    dfpj, dftw
    ], ignore_index=True)

combined_df.head(1000)
combined_df.shape

(80093, 2)

# TF-IDF for feature extraction

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X = tfidf_vectorizer.fit_transform(combined_df['Text']).toarray()
Y = combined_df['label']

# Data Splitting

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

# Classfication

Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

nb_model = GaussianNB()
nb_model.fit(X_train, Y_train)
y_pred_nb = nb_model.predict(X_test)
print(classification_report(Y_test, y_pred_nb))

              precision    recall  f1-score   support

    Grooming       0.90      0.98      0.94      7942
Non-grooming       0.98      0.89      0.93      8077

    accuracy                           0.94     16019
   macro avg       0.94      0.94      0.94     16019
weighted avg       0.94      0.94      0.94     16019

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model.fit(X_train, Y_train)
y_pred_lr = lr_model.predict(X_test)
print(classification_report(Y_test, y_pred_lr))

              precision    recall  f1-score   support

    Grooming       0.93      0.98      0.95      7942
Non-grooming       0.97      0.93      0.95      8077

    accuracy                           0.95     16019
   macro avg       0.95      0.95      0.95     16019
weighted avg       0.95      0.95      0.95     16019

SVM

In [ ]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC()
svm_model.fit(X_train, Y_train)

y_pred_svm = svm_model.predict(X_test)
print(classification_report(Y_test, y_pred_svm))

              precision    recall  f1-score   support

    Grooming       0.94      0.98      0.96      7942
Non-grooming       0.98      0.94      0.96      8077

    accuracy                           0.96     16019
   macro avg       0.96      0.96      0.96     16019
weighted avg       0.96      0.96      0.96     16019

Predict Function

In [ ]:
def predict_text(text_list, vectorizer, model):
    # Preprocess the input text
    processed_texts = [remove_stopwords(remove_symbols(text)) for text in text_list]

    # Transform the text using the trained TF-IDF vectorizer
    text_vectors = vectorizer.transform(processed_texts)

    # Convert the sparse matrix to a dense array if the model requires it
    if isinstance(model, GaussianNB):  # Check if the model is GaussianNB
        text_vectors = text_vectors.toarray()

    # Predict using the trained model
    predictions = model.predict(text_vectors)
    return predictions

In [ ]:
new_texts = [
    "Do you wanna come over to my place?",
    "Just a friendly chat, nothing suspicious.",
    "Can you meet me alone at the park tonight?",
    "Hey uhm, do you mind sending me nudes",
    "Do you wanna get freaky?",
    "Hello my name is Maroh",
    "1 plus 1 equals 2",
]

Result for Naive Bayes Model

In [ ]:
predicted_labels = predict_text(new_texts, tfidf_vectorizer, nb_model)

# Display predictions
for text, label in zip(new_texts, predicted_labels):
    print(f"Text: {text}\nPredicted Label: {label}\n")

Text: Do you wanna come over to my place?
Predicted Label: Grooming

Text: Just a friendly chat, nothing suspicious.
Predicted Label: Grooming

Text: Can you meet me alone at the park tonight?
Predicted Label: Grooming

Text: Hey uhm, do you mind sending me nudes
Predicted Label: Grooming

Text: Do you wanna get freaky?
Predicted Label: Grooming

Text: Hello my name is Maroh
Predicted Label: Grooming

Text: 1 plus 1 equals 2
Predicted Label: Grooming

Result for SVM Prediction

In [ ]:
predicted_labels = predict_text(new_texts, tfidf_vectorizer, svm_model)

# Display predictions
for text, label in zip(new_texts, predicted_labels):
    print(f"Text: {text}\nPredicted Label: {label}\n")

Text: Do you wanna come over to my place?
Predicted Label: Grooming

Text: Just a friendly chat, nothing suspicious.
Predicted Label: Grooming

Text: Can you meet me alone at the park tonight?
Predicted Label: Grooming

Text: Hey uhm, do you mind sending me nudes
Predicted Label: Grooming

Text: Do you wanna get freaky?
Predicted Label: Grooming

Text: Hello my name is Maroh
Predicted Label: Grooming

Text: 1 plus 1 equals 2
Predicted Label: Grooming

Result for Logistic regression model

In [ ]:
predicted_labels = predict_text(new_texts, tfidf_vectorizer, lr_model)

# Display predictions
for text, label in zip(new_texts, predicted_labels):
    print(f"Text: {text}\nPredicted Label: {label}\n")

Text: Do you wanna come over to my place?
Predicted Label: Grooming

Text: Just a friendly chat, nothing suspicious.
Predicted Label: Grooming

Text: Can you meet me alone at the park tonight?
Predicted Label: Grooming

Text: Hey uhm, do you mind sending me nudes
Predicted Label: Grooming

Text: Do you wanna get freaky?
Predicted Label: Grooming

Text: Hello my name is Maroh
Predicted Label: Grooming

Text: 1 plus 1 equals 2
Predicted Label: Grooming